-- =============================================================================
-- V11: 接口资源自动登记种子数据 + 超级管理员全量授权
-- =============================================================================
-- 背景：
--   项目共有 61 个带权限码的业务接口，但 sys_api_resource / sys_role_api 长期为空表，
--   导致「角色管理」无法勾选任何接口权限、@PreAuthorize 全部 403。
--   本脚本把扫描器（ApiResourceScanner）从 @PreAuthorize 注解解析出的权限码一次性落库，
--   并把全部接口授权给 SUPER_ADMIN。之后的增量由页面「扫描对比 → 同步」自助完成。
--
-- 数据来源：由 ApiResourceScanner 真实扫描 Spring MVC 路由表导出，非手工编写。
--   已过滤：免鉴权接口（/api/auth/login|refresh）、无权限码接口（/api/profile/** 等
--   走行级校验的个人接口）——这两类不参与权限码授权，落库会污染授权数据。
--
-- 幂等性：
--   全部语句走 INSERT IGNORE / INSERT ... SELECT NOT EXISTS，重复执行结果一致。
--   sys_api_resource 依赖主键幂等，sys_role_api 依赖 (role_id, api_id) 查重。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) 接口资源种子数据
-- -----------------------------------------------------------------------------
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000001, 0, '新建公告（初始为草稿）', 'system:announcement:create', 'POST', '/api/system/announcements', 'AnnouncementController#create', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000002, 0, '分页查询公告（支持标题/内容关键词搜索）', 'system:announcement:read', 'GET', '/api/system/announcements/page', 'AnnouncementController#page', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000003, 0, '删除公告（逻辑删除）', 'system:announcement:delete', 'DELETE', '/api/system/announcements/{id}', 'AnnouncementController#delete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000004, 0, '公告详情（累加浏览次数）', 'system:announcement:read', 'GET', '/api/system/announcements/{id}', 'AnnouncementController#get', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000005, 0, '编辑公告（仅草稿/已下线可编辑）', 'system:announcement:update', 'PUT', '/api/system/announcements/{id}', 'AnnouncementController#update', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000006, 0, '下线公告', 'system:announcement:publish', 'POST', '/api/system/announcements/{id}/offline', 'AnnouncementController#offline', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000007, 0, '发布公告（支持定时生效：publishAt 为空则立即生效）', 'system:announcement:publish', 'POST', '/api/system/announcements/{id}/publish', 'AnnouncementController#publish', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000008, 0, '切换置顶', 'system:announcement:update', 'POST', '/api/system/announcements/{id}/toggle-top', 'AnnouncementController#toggleTop', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000009, 0, '接口资源列表', 'system:api:read', 'GET', '/api/system/api-resources', 'ApiResourceController#list', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000010, 0, '注册接口资源', 'system:api:create', 'POST', '/api/system/api-resources', 'ApiResourceController#create', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000011, 0, '扫描接口资源并预览差异（不写库）', 'system:api:read', 'GET', '/api/system/api-resources/scan', 'ApiResourceController#scanPreview', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000012, 0, '执行接口资源扫描同步（写库）', 'system:api:sync', 'POST', '/api/system/api-resources/scan/sync', 'ApiResourceController#sync', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000013, 0, '删除接口资源', 'system:api:delete', 'DELETE', '/api/system/api-resources/{id}', 'ApiResourceController#delete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000014, 0, '更新接口资源', 'system:api:update', 'PUT', '/api/system/api-resources/{id}', 'ApiResourceController#update', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000015, 0, '配置列表', 'system:config:read', 'GET', '/api/system/configs', 'ConfigController#list', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000016, 0, '创建配置', 'system:config:create', 'POST', '/api/system/configs', 'ConfigController#create', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000017, 0, '按配置键动态读取', 'system:config:read', 'GET', '/api/system/configs/key/{key}', 'ConfigController#getByKey', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000018, 0, '删除配置', 'system:config:delete', 'DELETE', '/api/system/configs/{id}', 'ConfigController#delete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000019, 0, '更新配置', 'system:config:update', 'PUT', '/api/system/configs/{id}', 'ConfigController#update', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000020, 0, '字典数据列表（按字典类型筛选）', 'system:dict:read', 'GET', '/api/system/dict-data', 'DictDataController#list', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000021, 0, '创建字典数据', 'system:dict:create', 'POST', '/api/system/dict-data', 'DictDataController#create', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000022, 0, '删除字典数据', 'system:dict:delete', 'DELETE', '/api/system/dict-data/{id}', 'DictDataController#delete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000023, 0, '更新字典数据', 'system:dict:update', 'PUT', '/api/system/dict-data/{id}', 'DictDataController#update', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000024, 0, '字典类型列表', 'system:dict:read', 'GET', '/api/system/dict-types', 'DictTypeController#list', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000025, 0, '创建字典类型', 'system:dict:create', 'POST', '/api/system/dict-types', 'DictTypeController#create', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000026, 0, '删除字典类型（存在字典数据时拒绝）', 'system:dict:delete', 'DELETE', '/api/system/dict-types/{id}', 'DictTypeController#delete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000027, 0, '更新字典类型', 'system:dict:update', 'PUT', '/api/system/dict-types/{id}', 'DictTypeController#update', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000028, 0, '创建菜单', 'system:menu:create', 'POST', '/api/system/menus', 'MenuController#create', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000029, 0, '菜单树', 'system:menu:read', 'GET', '/api/system/menus/tree', 'MenuController#tree', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000030, 0, '删除菜单', 'system:menu:delete', 'DELETE', '/api/system/menus/{id}', 'MenuController#delete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000031, 0, '更新菜单', 'system:menu:update', 'PUT', '/api/system/menus/{id}', 'MenuController#update', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000032, 0, '发送站内信（单条指定接收人，或按角色/部门批量发送）', 'system:message:send', 'POST', '/api/system/messages/send', 'MessageController#send', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000033, 0, '我发出的消息分页（含已读统计）', 'system:message:read', 'GET', '/api/system/messages/sent', 'MessageController#sent', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000034, 0, '异常日志分页（按时间范围查询关键接口/任务失败记录）', 'system:monitor:read', 'GET', '/api/system/monitor/error-logs', 'MonitorController#errorLogs', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000035, 0, '异常日志按模块/错误码聚合', 'system:monitor:read', 'GET', '/api/system/monitor/error-summary', 'MonitorController#errorSummary', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000036, 0, '实时运行指标（CPU/内存/磁盘/JVM）', 'system:monitor:read', 'GET', '/api/system/monitor/metrics', 'MonitorController#metrics', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000037, 0, '在线会话明细（可按用户名/姓名筛选）', 'system:monitor:read', 'GET', '/api/system/monitor/online-sessions', 'MonitorController#onlineSessions', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000038, 0, '在线用户与会话汇总', 'system:monitor:read', 'GET', '/api/system/monitor/online-summary', 'MonitorController#onlineSummary', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000039, 0, '手动触发一次采样（供前端刷新按钮使用）', 'system:monitor:read', 'POST', '/api/system/monitor/sample', 'MonitorController#sample', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000040, 0, '历史采样趋势（按时间范围）', 'system:monitor:read', 'GET', '/api/system/monitor/samples', 'MonitorController#samples', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000041, 0, '创建机构', 'system:org:create', 'POST', '/api/system/orgs', 'OrgController#create', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000042, 0, '机构树', 'system:org:read', 'GET', '/api/system/orgs/tree', 'OrgController#tree', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000043, 0, '删除机构（存在子机构时拒绝）', 'system:org:delete', 'DELETE', '/api/system/orgs/{id}', 'OrgController#delete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000044, 0, '更新机构（支持调整上级与层级移动）', 'system:org:update', 'PUT', '/api/system/orgs/{id}', 'OrgController#update', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000045, 0, '角色列表', 'system:role:read', 'GET', '/api/system/roles', 'RoleController#list', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000046, 0, '创建角色', 'system:role:create', 'POST', '/api/system/roles', 'RoleController#create', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000047, 0, '删除角色', 'system:role:delete', 'DELETE', '/api/system/roles/{id}', 'RoleController#delete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000048, 0, '角色详情（含菜单/接口权限）', 'system:role:read', 'GET', '/api/system/roles/{id}', 'RoleController#get', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000049, 0, '更新角色', 'system:role:update', 'PUT', '/api/system/roles/{id}', 'RoleController#update', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000050, 0, '创建用户', 'system:user:create', 'POST', '/api/system/users', 'UserController#create', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000051, 0, '分页查询用户', 'system:user:read', 'GET', '/api/system/users/page', 'UserController#page', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000052, 0, '删除用户（物理删除/硬删除）', 'system:user:delete', 'DELETE', '/api/system/users/{id}', 'UserController#delete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000053, 0, '用户详情', 'system:user:read', 'GET', '/api/system/users/{id}', 'UserController#get', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000054, 0, '更新用户', 'system:user:update', 'PUT', '/api/system/users/{id}', 'UserController#update', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000055, 0, '重置密码', 'system:user:update', 'POST', '/api/system/users/{id}/reset-password', 'UserController#resetPassword', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000056, 0, '我发起的流程', 'workflow:instance:read', 'GET', '/api/workflow/instances/mine', 'InstanceController#mine', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000057, 0, '发起审批流程', 'workflow:instance:start', 'POST', '/api/workflow/instances/start', 'InstanceController#start', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000058, 0, '流程审批记录', 'workflow:instance:read', 'GET', '/api/workflow/instances/{processInstanceId}/records', 'InstanceController#records', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000059, 0, '审批/驳回任务', 'workflow:task:approve', 'POST', '/api/workflow/tasks/complete', 'TaskController#complete', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000060, 0, '我的待办任务', 'workflow:task:read', 'GET', '/api/workflow/tasks/mine', 'TaskController#mine', 'REQUIRED', 'ACTIVE', 'NORMAL');
INSERT INTO sys_api_resource (id, tenant_id, resource_name, permission_code, http_method, path_pattern, controller_method, auth_mode, status, risk_level) VALUES (900000000061, 0, '转办任务', 'workflow:task:transfer', 'POST', '/api/workflow/tasks/transfer', 'TaskController#transfer', 'REQUIRED', 'ACTIVE', 'NORMAL');

-- -----------------------------------------------------------------------------
-- 2) 超级管理员全量授权（解开「要同步需权限、要有权限得先同步」的死锁）
--    仅对 SUPER_ADMIN 生效；其他角色的授权仍由「角色管理」页面显式勾选。
-- -----------------------------------------------------------------------------
INSERT IGNORE INTO sys_role_api (tenant_id, role_id, api_id, created_at)
SELECT 0, r.id, a.id, CURRENT_TIMESTAMP(3)
FROM sys_role r
         JOIN sys_api_resource a
WHERE r.role_code = 'SUPER_ADMIN'
  AND NOT EXISTS (SELECT 1
                  FROM sys_role_api ra
                  WHERE ra.role_id = r.id
                    AND ra.api_id = a.id);
